/*
 * License:
 * See LICENSE.md included in the release download, or at https://github.com/WoutProvost/FCNPC-A.I./blob/master/LICENSE.md if not included.

 * Credits:
 * See CREDITS.md included in the release download, or at https://github.com/WoutProvost/FCNPC-A.I./blob/master/CREDITS.md if not included.

 * Changelog:
 * See CHANGELOG.md included in the release download, or at https://github.com/WoutProvost/FCNPC-A.I./blob/master/CHANGELOG.md if not included.

 * Documentation:
 * Every function, callback or define is extensively explained at https://github.com/WoutProvost/FCNPC-A.I./wiki and its various subsections.
*/

#if defined _MMO_included
	#endinput
#endif
#define _MMO_included
#pragma library MMO

//========================================FAKE NATIVES========================================
/*

*/

//========================================CALLBACKS========================================


//========================================DEFINES========================================


//========================================VARIABLES========================================


//========================================INTERNAL FUNCTIONS========================================


//========================================HOOKED CALLBACKS========================================


//========================================HOOKED FUNCTIONS========================================


//========================================FUNCTIONS========================================